export const routes = {
  public: {
    home: "/",
    about: "/about",
    organizations: "/organizations",
    org3doors: "/organizations/3doors",
    orgPalaverInstitute: "/organizations/palaverinstitute",
    orgDewiseFoundation: "/organizations/dewisefoundation",
    communityImpact: "/community-impact",
    achievements: "/achievements",
    media: "/media",
    writing: "/writing",
    writingBySlug: (slug: string) => `/writing/${slug}`,
    research: "/research",
    contact: "/contact",
  },
  admin: {
    dashboard: "/admin",
    writing: "/admin/writing",
    research: "/admin/research",
    impact: "/admin/community-impact",
    achievements: "/admin/achievements",
    mediaAppearances: "/admin/media-appearances",
    metrics: "/admin/metrics",
    testimonials: "/admin/testimonials",
    leads: "/admin/leads",
    assets: "/admin/assets",
    exitIntent: "/admin/exit-intent",
    navigation: "/admin/navigation",
    analytics: "/admin/analytics",
  },
  dev: {
    ui: "/dev/ui",
  },
} as const;
